package bank_enums;

public enum UserRole {
    NATURAL_PERSON_CUSTOMER,
    BUSINESS_CUSTOMER,
    TELLER_EMPLOYEE,
    COMMERCIAL_EMPLOYEE,
    BUSINESS_EMPLOYEE,
    BUSINESS_SUPERVISOR,
    INTERNAL_ANALYST
}